<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="FgoPet.Windows.Tests" />
    <ProjectReference Include="../../../src/FgoPet.Extensibility/FgoPet.Extensibility.csproj" />
    <ProjectReference Include="../../../src/FgoPet.Platform/Storage/FgoPet.Platform.Storage.csproj" />
  </ItemGroup>
</Project>
